# Default values for angular.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---
#namespace: eventat-api-staging
replicaCount: 2

image:
  repository: registry.digitalocean.com/eventat/angular-prod
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"


service:
  type: ClusterIP
  port: 80
  containerPort: 4000
server_name: dev2.eventat.com

ingress:
  enabled: true
  className: "nginx"
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: dev2.eventat.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
     - hosts:
        - dev2.eventat.com
  staff:
    enabled: false
    # Change this to true if you want to use the staff subdomain.
    staff_url: staff.eventat.com      
#Enable this if you want to use the taints and tolerations
tolerations:
  effect: NoSchedule
  key: env
  operator: Equal
  value: frontend
nodeSelector: frontend-pool
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60
resources:
  requestsCPU: "100m"
  requestsMemory: "200Mi"
